ouraapp/calendar/models.py
from ouraapp.extensions import db


class Events(db.Model):
    __tablename__ = 'events'
    id = db.Column(db.Integer, unique=True, primary_key=True)
    day_id = db.Column(db.Integer)
    date = db.Column(db.Date)
    title = db.Column(db.String)
    score = db.Column(db.Float)
    event = db.Column(db.JSON)
    subclass = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

ouraapp/insights/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, DateField, IntegerField
from wtforms.validators import Optional
from ouraapp.dashboard.models import Tag
from wtforms_sqlalchemy.fields import QuerySelectMultipleField


def tag_query():
    return Tag.query.order_by(Tag.tag)


class FilterForm(FlaskForm):
    tag_filter = QuerySelectMultipleField('Tags ', query_factory=tag_query)

    sleep_filter = SelectField('Sleep ',
                               choices=[
                                   '', 'Sleep Score', 'Efficiency Score',
                                   'Food Timing 0-1.5', 'Food Timing 1.5-3',
                                   'Food Timing 3-4.5', 'Food Timing 4.5+'
                               ])
    sleep_operator = SelectField(
        choices=['', '>', '<', 'between'],
        render_kw={'onchange': "secondField('sleep_second')"})
    sleep_first = IntegerField()
    sleep_second = IntegerField(validators=[Optional()])

    readiness_filter = SelectField(
        'Readiness ',
        choices=['', 'Readiness', 'Recovery Index', 'Temperature Score'])
    readiness_operator = SelectField(choices=['', '>', '<', 'between'])
    readiness_first = IntegerField()
    readiness_second = IntegerField(validators=[Optional()])

    wellness_filter = SelectField(
        'Wellness ', choices=['', 'Focus', 'Energy', 'Mood', 'Stress'])
    wellness_operator = SelectField(choices=['', '>', '<', 'between'])
    wellness_first = IntegerField()
    wellness_second = IntegerField(validators=[Optional()])

    workout_filter = SelectField('Workout ', choices=['', 'Grade', 'Soreness'])
    workout_operator = SelectField(choices=['', '>', '<', 'between'])
    workout_first = IntegerField()
    workout_second = IntegerField(validators=[Optional()])
    start_date = DateField('Date Range:', format='%Y-%m-%d')
    end_date = DateField(format='%Y-%m-%d')

    submit = SubmitField("Submit Filters")

ouraapp/profile/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Email, Optional


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password1 = PasswordField(
        'New Password (Optional)',
        validators=[EqualTo('password2', message='Passwords Must Match!')])
    password2 = PasswordField('Confirm New Password')
    email = StringField('Email', validators=[DataRequired(), Email()])
    name = StringField('Name', validators=[DataRequired()])
    oura_access_token = StringField('Oura Access Token',
                                    validators=[Optional()])
    submit = SubmitField('Submit')

ouraapp/calendar/__init__.py
from flask import Blueprint

bp = Blueprint('calendar', __name__)

from ouraapp.calendar import routes

ouraapp/calendar/routes.py
from flask import render_template, session, redirect, url_for, request, Blueprint
from ouraapp.models import Day
from flask_login import login_required
from .helpers import get_db_events
import logging
from ouraapp.calendar import bp

logger = logging.getLogger("ouraapp")


@bp.route('/calendar', methods=['GET', 'POST'])
@login_required
def calendar():
    session['url'] = url_for('dashboard.log', page_id=None)
    return render_template('calendar.html', events=get_db_events())


@bp.route('/process', methods=['POST'])
@login_required
def process():
    ''' Used to process ajax call for calendar event clicks.
  Routes to the correct index page based on the page_id/dates.
  '''
    date_str = request.form.get('date_str')
    clicked_day_obj = Day.query.filter(Day.date_str == date_str).first()
    return redirect(url_for('dashboard.log', page_id=clicked_day_obj.id))

ouraapp/insights/__init__.py
from flask import Blueprint

bp = Blueprint('insights', __name__)

from ouraapp.insights import routes

ouraapp/insights/routes.py
from flask import render_template, request
from .helpers import get_overall_averages, get_filters, get_date_range, get_filtered_avgs
from flask_login import login_required, current_user
from .forms import FilterForm
from ouraapp.dashboard.models import Sleep
import logging
from ouraapp.insights import bp

logger = logging.getLogger("ouraapp")


@bp.route('/insights', methods=['GET', 'POST'])
@login_required
def insights():
    filter_form = FilterForm()
    averages = get_overall_averages()
    total_days = len(
        Sleep.query.filter(Sleep.user_id == current_user.id).order_by(
            Sleep.id).all())
    filter_objs, filter_avgs, filtered_days = None, None, None
    if request.method == "POST":
        date_range = get_date_range(filter_form)
        filter_objs = get_filters(filter_form, date_range)
        filter_avgs = get_filtered_avgs(filter_objs)
        filtered_days = len(filter_objs)
    return render_template('insights.html',
                           averages=averages,
                           filter_form=filter_form,
                           filter_objs=filter_objs,
                           filter_avgs=filter_avgs,
                           filtered_days=filtered_days,
                           total_days=total_days)

ouraapp/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from ouraapp.profile import routes

ouraapp/profile/routes.py
from flask_login import current_user, login_required
from flask_wtf import FlaskForm
from flask import request, redirect, url_for, render_template
from ouraapp.auth.models import User
from ouraapp.extensions import db
from .forms import EditProfileForm
from ouraapp.profile import bp
from werkzeug.security import generate_password_hash, check_password_hash


@bp.route(f'/profile/<int:edit>', methods=['GET', 'POST'])
@login_required
def profile(edit):
    user = User.query.filter_by(id=current_user.id).first()
    username = user.username
    name = user.name
    password = user.password_hash
    oura_access_token = user.oura_access_token
    join_date = user.join_date
    email = user.email
    form = EditProfileForm(username=username,
                           email=email,
                           name=name,
                           oura_access_token=oura_access_token)

    if form.validate_on_submit():
        user.username = form.username.data
        user.name = form.name.data
        user.email = form.email.data
        if form.password1.data:
            user.password = form.password1.data
        user.oura_access_token = form.oura_access_token.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('profile.profile', edit=0))

    return render_template('profile.html',
                           form=form,
                           username=username,
                           name=name,
                           oura_access_token=oura_access_token,
                           join_date=join_date,
                           edit=edit,
                           password=password,
                           email=email)

ouraapp/templates/base.html
<!doctype html>
<html>

<head>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="">Jack's Wellness App</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


            <div class="collapse navbar-collapse" id="navbarToggler">


            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/dashboard/log">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/calendar">Calendar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/insights">Insights</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('profile.profile', edit=0)}}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/auth/register">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/auth/logout">Log Out</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8b31cf3499.js" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}


</head>

<body>
    <br>
    {% block content %}
{% for message in get_flashed_messages() %}

<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>


{% endfor %}
    {% endblock %}





    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
    <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
</body>


</html>

ouraapp/templates/calendar.html
{% extends "base.html" %}

import { Calendar } from '@fullcalendar/core';
import interactionPlugin from '@fullcalendar/interaction';



{% block head %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
{% endblock %}

{% block content %}


<div class="container">
  <div id="calendar"></div>
  <script>
  const sleep_color = 'black';
  const swim_color = 'light-blue';
  const journal_color = '#08088A';
  const weights_color = 'blue';
  const hike_color = 'green';


    let calendarEl = document.getElementById
    ('calendar');

    let calendar = new FullCalendar.Calendar(calendarEl, {
      events: [
      {% for event_obj in events %}
        {
      {% if event_obj.subclass == 'Oura' %}
        backgroundColor: sleep_color,
        borderColor: sleep_color,
        title: ' {{ event_obj.title }}' + ' {{ event_obj.score|round|int }}',
      {% if event_obj.title == 'Sleep' %}
        icon: "bed",
        {% elif event_obj.title == 'Readiness' %}
        icon: "bolt",
        {% endif %}

      {% else %}
       {% if event_obj.title == 'Weights' %}
            icon: "dumbbell",
        {% elif event_obj.title == 'Wellness' %}
            icon: "spa",
        {% elif event_obj.title == 'Swim' %}
            icon: "person-swimming",
        {% elif event_obj.title == 'Hike' %}
            icon: "person-hiking",
        {% endif %}
        {% if not event_obj.title == 'Wellness' and event_obj.score %}
            title: ' {{ event_obj.title }}' + ' {{ event_obj.score|round|int }}',
        {% else %}
            title: ' {{ event_obj.title }}' + ' {{ event_obj.score }}',
      {% endif %}
      {% endif %}
      id: '{{ event_obj.day_id }}',
      start : '{{ event_obj.date }}',
      url: '{{ url_for('dashboard.log', page_id = event_obj.day_id) }}',



      {% if event_obj.title == 'Wellness' %}
      backgroundColor: journal_color,
      borderColor: journal_color,
      {% elif event_obj.title == 'Weights' %}
      backgroundColor: weights_color,
      borderColor: weights_color,
      {% elif event_obj.title == 'Swim' %}
      backgroundColor: swim_color,
      borderColor: swim_color,
      {% elif event_obj.title == 'Hike' %}
      backgroundColor: hike_color,
        borderColor: hike_color,
      {% endif %}
      },


      {% endfor %}
      ],

      eventDidMount: function(info) {
        console.log(info);
        var icon = info.event.extendedProps.icon;
          if (info.event.extendedProps.icon) {
              $(info.el).find('.fc-event-title').prepend("<i class='fa fa-" + icon + "'></i>");
          }
        },
      eventClick: function(info) {
        if (info.event.url) {
          window.open(info.event.url);
        }
      },
      dateClick: function(date) {
        var date_str = date.dateStr;
        var xhr = new XMLHttpRequest();
        $.ajax({
          data : {'date_str' : date_str},
          url : '{{url_for('calendar.process')}}',
          method : 'POST',
          cache: false,
          xhr: function(){
            return xhr;
          }
        }).done (function(response){
          document.write(response)
          window.history.pushState(undefined, '', xhr.responseURL)
        })
      }
    });
  calendar.render();
  </script>
</div>
{% endblock %}

ouraapp/templates/create_template.html
{% extends "base.html" %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/weights.css') }}"
/>
{% endblock %} {% block content %}

<div class="container create_template">
  <h1>Workout Template (Day {{day}})</h1>
  <br /><br />

  <form method="POST">
    {{ form.hidden_tag() }} {% for field in form.exercise_params %}
    <div class="ex-num">{{loop.index}}.</div>
    <div class="container-smooth exercise-cluster">
      <div class="row">
        <div class="col-md-5 excs">
          {{ field.excs.label(class="form-label") }}<br />
          {{ field.excs()}}
        </div>
        <div class="col-md-4 excs">
          Rep Range: <br />
          {{ field.reps1()}} - {{ field.reps2()}}
        </div>

        <div class="col-md-3 excs">
          {{ field.sets.label(class="form-label") }}<br />
          {{ field.sets()}}
        </div>
      </div>
    </div>
    <br />
    <hr class="dotted" />
    <br />
    {% endfor %}
    <br />
    {{ form.submit(class="btn btn-secondary") }}
  </form>
</div>
{% endblock %}

ouraapp/templates/index.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css') }}">
{% endblock %}


{% block content %}
<body>
<div class="container">


    <form method="POST" class="form">
        {{ login_form.hidden_tag() }}
        <h2>Login</h2>
        <br /><br />
        {{ login_form.username.label(class="form-label") }}

        {{ login_form.username(class="form-control") }}

        {{ login_form.password.label(class="form-label") }}

        {{ login_form.password(class="form-control") }}
        <br />


        <br />

        {{ login_form.submit(class="btn btn-secondary") }}


        <div>
            <br />
            <span>Don't have an account? <a href="{{ url_for('auth.register') }}">Sign up.</a></span></br>
            <span>Forgot Password? <a href="{{ url_for('auth.reset_password_request') }}">Click to Reset.</a></span></br>
        </div>
    </form>




</div>
</body>
{% endblock %}

ouraapp/templates/init_template.html
{% extends "base.html" %}

{% block head %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/weights.css') }}">

{% endblock %}

{% block content %}



<div class="container">
    <h1>Initialize Workout Template</h1>
<form method="POST">
    {{ init_form.hidden_tag() }}


    <div class="row form-fields">
        <div class="col left-input">{{ init_form.name_workout_plan.label(class="form-label") }} <br>
        {{ init_form.name_workout_plan()}}<br><br></div>
        <div class="col right-input">
            {{ init_form.days.label(class="form-label") }} <br>
            {{ init_form.days()}}
        </div>
    </div>

    <hr class="dotted">
    <br>

    <div class="one-rep-max">
    <h5>Current One-Rep Maxes (optional):</h5>
    <br>

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>
                        Exercise
                    </th>
                    <th>
                        Weight
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ init_form.bench_pr.label(class="form-label") }}</td>
                    <td>{{ init_form.bench_pr()}}</td>
                </tr>
                <tr>
                    <td>{{ init_form.squat_pr.label(class="form-label") }}</td>
                    <td>{{ init_form.squat_pr()}}</td>
                </tr>
                <tr>
                    <td>{{ init_form.deadlift_pr.label(class="form-label") }}</td>
                    <td>{{ init_form.deadlift_pr()}}</td>
                </tr>
                <tr>
                    <td>{{ init_form.ohp_pr.label(class="form-label") }}</td>
                    <td>{{ init_form.ohp_pr()}}</td>
                </tr>

                {% for entry in init_form.custom_prs %}

                <tr class='optional-row' id='{{loop.index}}'>
                    <td>
                        {{ entry.custom_pr_name()}}
                    </td>
                    <td>
                        {{ entry.custom_pr_weight()}}
                    </td>
                </tr>



                {% endfor %}



            <tr>
                <td></td>
                <td><button type="button" class="minus">-</button><button type="button" class="plus">+</button></td>
            </tr>
        </table>
        </tbody>

    {{ init_form.submit(class="btn btn-secondary submit") }}
        </div>

</form>



</div>

<script>
    let row_id = 0;

    // console.log(name);
    // let displayIndex = document.getElementById(row_id);
    let counterPlus = document.querySelector('.plus');
    let counterMinus = document.querySelector('.minus');

    if (row_id == 4) {
        counterPlus.style.display = 'none';
    }

    counterPlus.addEventListener("click", ()=>{
        if (row_id < 4) {
            row_id++;
            document.getElementById(row_id).style.display = "table-row";
        }
        if (row_id == 4) {
            counterPlus.style.display = 'none';
        }

    });

    counterMinus.addEventListener("click", () => {
            document.getElementById(row_id).style.display = "none";
            if (row_id > 0) {
                row_id--;
            }
            if (row_id < 4) {
                counterPlus.style.display = 'table-row';
            }

        });


</script>


{% endblock %}

ouraapp/templates/insights.html
{% extends "base.html" %}


{% block content %}
<script>
    function secondField(field_name) {
        let showField = document.getElementById(field_name);
        if (showField.value !== 'between') {
            showField.style.display = 'none';
        }

    }
</script>



<div class='container-fluid'>
    <h4>Insight Filters</h4>
    <hr>
    <form method="POST">
        {{ filter_form.csrf_token() }}
        {{ filter_form.hidden_tag() }}

        {{filter_form.start_date.label}} {{filter_form.start_date(class='datepicker')}} {{filter_form.hidden_tag()}}
        {{filter_form.end_date(class='datepicker')}} {{filter_form.hidden_tag()}}
        <br><br>
        <div class="row">
            <div class="col-lg"> {{ filter_form.sleep_filter.label(class="form-label" ) }} <i
                    class="fa-solid fa-bed"></i>
                <br>
                {{ filter_form.sleep_filter()}}
                {{ filter_form.sleep_operator()}}
                <br>
                {{ filter_form.sleep_first()}}
                {{ filter_form.sleep_second() }}
            </div>
            <div class="col-lg">
                {{ filter_form.readiness_filter.label(class="form-label") }} <i class="fa-solid fa-bolt"></i>
                <br>
                {{ filter_form.readiness_filter()}}
                {{ filter_form.readiness_operator()}}
                <br>
                {{ filter_form.readiness_first()}}
                {{ filter_form.readiness_second()}}
                <br><br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg">
                {{ filter_form.wellness_filter.label(class="form-label") }} <i class="fa-solid fa-spa"></i>
                <br>
                {{ filter_form.wellness_filter()}}
                {{ filter_form.wellness_operator()}}
                <br>
                {{ filter_form.wellness_first()}}
                {{ filter_form.wellness_second()}}<br>

            </div>
            <div class="col-lg">{{ filter_form.workout_filter.label(class="form-label" ) }} <i
                    class="fa-solid fa-person-running"></i>
                <br>
                {{ filter_form.workout_filter()}}
                {{ filter_form.workout_operator()}}
                <br>
                {{ filter_form.workout_first()}}
                {{ filter_form.workout_second()}}
                <br><br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg">
                {{ filter_form.tag_filter.label(class="form-label") }} <i class="fa-solid fa-tags"></i><br>
                {{ filter_form.tag_filter()}}
            </div>
            <div class="col-lg"> <br><br><br>{{ filter_form.submit(class="btn btn-dark" ) }} </div><br>
        </div>
    </form>

    <hr>

    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Category</th>
                <th scope="col">Overall Average ({{total_days}}) </th>
                {% if filter_avgs %}
                <th scop="col">Filtered Average ({{filtered_days}})</th>
                {% endif %}
                <!-- <th scope="col">Last</th>
            <th scope="col">Handle</th> -->
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Total Sleep</th>
                <td>{{averages['avg_total_sleep']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_total_sleep']}}</td>
                {% endif %}
                <!-- <td></td> -->
            </tr>
            <tr>
                <th scope="row">Sleep Score</th>
                <td>{{averages['avg_sleep_score']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_sleep_score']}}</td>
                {% endif %}
                <!-- <td></td> -->
            </tr>
            <tr>
                <th scope="row">REM Score</th>
                <td>{{averages['avg_rem_score']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_rem_score']}}</td>
                {% endif %}
                <!-- <td>@fat</td> -->
            </tr>
            <tr>
                <th scope="row">Deep Score</th>
                <td>{{averages['avg_deep_score']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_deep_score']}}</td>
                {% endif %}
                <!-- <td>@twitter</td> -->
            </tr>
            <tr>
                <th scope="row">Sleep Efficiency</th>
                <td>{{averages['avg_sleep_efficiency']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_sleep_efficiency']}}</td>
                {% endif %}
                <!-- <td>the Bird</td>
            <td>@twitter</td> -->
            </tr>
            <tr>
                <th scope="row">Readiness Score</th>
                <td>{{averages['avg_readiness_score']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_readiness_score']}}</td>
                {% endif %}
                <!-- <td>the Bird</td>
            <td>@twitter</td> -->
            </tr>
            <tr>
                <th scope="row">Recovery Index</th>
                <td>{{averages['avg_recovery_index']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_recovery_index']}}</td>
                {% endif %}
                <!-- <td>the Bird</td>
            <td>@twitter</td> -->
            </tr>
            <tr>
                <th scope="row">HRV Balance</th>
                <td>{{averages['avg_hrv_balance']}}</td>
                {% if filter_avgs %}
                <td>{{filter_avgs['avg_hrv_balance']}}</td>
                {% endif %}
                <!-- <td>the Bird</td>
            <td>@twitter</td> -->
            </tr>
        </tbody>
    </table>
    {% endblock %}
</div>

ouraapp/templates/profile.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css') }}">
{% endblock %}

{% block content %}

<!-- {% for message in get_flashed_messages() %}

<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>


{% endfor %} -->

<body>
    <div class="container">


        {% if edit == 1 %}

        <form method="POST" class="form">
            {{ form.hidden_tag() }}
            <h2>Edit Profile</h2>
            <br /><br />
            {{ form.username.label(class="form-label") }}

            {{ form.username(class="form-control") }}

            {{ form.name.label(class="form-label")}}

            {{ form.name(class="form-control")}}

            {{ form.email.label(class="form-label") }}

            {{ form.email(class="form-control") }}

            {{ form.password1.label(class="form-label")}}

            {{ form.password1(class="form-control")}}

            {{ form.password2.label(class="form-label")}}

            {{ form.password2(class="form-control")}}

            {{ form.oura_access_token.label(class="form-label")}}

            {{ form.oura_access_token(class="form-control")}}
            <br />


            <br />

            {{ form.submit(class="btn btn-secondary") }} <a href="{{url_for('profile.profile', edit=0)}}" class="btn btn-info">View Profile</a>


        </form>

        {% else %}
        <br><br>
        <h2>User Profile</h2>

        <br /><br />
        <h6>Username:</h6> <p>{{username}}</p>
        <h6>Name:</h6> <p>{{name}}</p>
        <h6>Email:</h6> <p>{{email}}</p>
        <h6>Oura Access Token:</h6> <p>{{oura_access_token}}</p>
        <h6>Join Date:</h6> <p>{{join_date}}</p>
        <a href="{{url_for('profile.profile', edit=1)}}" class="btn btn-info">Edit Profile</a><br>
        {% endif %}
    </div>
</body>
{% endblock %}

ouraapp/templates/registration.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css') }}">
{% endblock %}

{% block content %}

<!-- {% for message in get_flashed_messages() %}

<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>


{% endfor %} -->

<body>
    <div class="container">


        <form method="POST" class="form">
            {{ form.hidden_tag() }}
            <h2>Register</h2>
            <br /><br />
            {{ form.username.label(class="form-label") }}

            {{ form.username(class="form-control") }}

            {{ form.name.label(class="form-label")}}

            {{ form.name(class="form-control")}}

            {{ form.email.label(class="form-label") }}

            {{ form.email(class="form-control") }}

            {{ form.password1.label(class="form-label")}}

            {{ form.password1(class="form-control")}}

            {{ form.password2.label(class="form-label")}}

            {{ form.password2(class="form-control")}}

            {{ form.oura_access_token.label(class="form-label")}}

            {{ form.oura_access_token(class="form-control")}}
            <br />


            <br />

            {{ form.submit(class="btn btn-secondary") }}


        </form>

    </div>
</body>
{% endblock %}

ouraapp/templates/reset_password_request.html
{% extends "base.html" %}

{% block content %}
<h1>Reset Password</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.email.label }}<br>
        {{ form.email(size=64) }}<br>
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}